package main.ui.dialog

import main.App
import main.ui.resource.AppImage
import main.ui.resource.AppText
import main.util.Fn
import main.util.IO
import java.awt.event.ActionEvent
import javax.swing.*

/**
 *
 * @author Bunnyspa
 */
class DonationDialog private constructor(app: App) : JDialog() {
    private val app: App
    private fun init() {
        title = "Donation"
        paypalQRLabel!!.icon = AppImage.PAYPALQR
        paypalQRLabel!!.text = ""
        paypalQRDescLabel!!.icon = AppImage.PAYPAL
        closeButton!!.text = app.getText(AppText.ACTION_CLOSE)
        addListeners()

//        Dimension d = getPreferredSize();
//        d.height = app.mf.getPreferredDialogSize().height;
//        setPreferredSize(d);
        pack()
    }

    private fun addListeners() {
        Fn.addEscDisposeListener(this)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {
        paypalButton = JButton()
        jPanel1 = JPanel()
        paypalQRLabel = JLabel()
        paypalQRDescLabel = JLabel()
        closeButton = JButton()
        defaultCloseOperation = DISPOSE_ON_CLOSE
        title = "모두 적용"
        modalityType = ModalityType.APPLICATION_MODAL
        isResizable = false
        type = Type.UTILITY
        paypalButton!!.text = "Go to PayPal website"
        paypalButton!!.addActionListener { evt: ActionEvent -> paypalButtonActionPerformed(evt) }
        paypalQRLabel!!.text = "QR"
        paypalQRDescLabel!!.horizontalAlignment = SwingConstants.CENTER
        paypalQRDescLabel!!.text = "<html><center>PayPal<br>QR Code</center></html?"
        val jPanel1Layout = GroupLayout(jPanel1)
        jPanel1!!.layout = jPanel1Layout
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(
                    paypalQRLabel,
                    GroupLayout.DEFAULT_SIZE,
                    GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE.toInt()
                )
                .addComponent(paypalQRDescLabel)
        )
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    jPanel1Layout.createSequentialGroup()
                        .addComponent(
                            paypalQRDescLabel,
                            GroupLayout.PREFERRED_SIZE,
                            GroupLayout.DEFAULT_SIZE,
                            GroupLayout.PREFERRED_SIZE
                        )
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paypalQRLabel)
                )
        )
        closeButton!!.text = "cancel"
        closeButton!!.addActionListener { evt: ActionEvent -> closeButtonActionPerformed(evt) }
        val layout = GroupLayout(contentPane)
        contentPane.layout = layout
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(
                                    layout.createSequentialGroup()
                                        .addComponent(paypalButton)
                                        .addPreferredGap(
                                            LayoutStyle.ComponentPlacement.RELATED,
                                            GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE.toInt()
                                        )
                                        .addComponent(closeButton)
                                )
                                .addGroup(
                                    layout.createSequentialGroup()
                                        .addComponent(
                                            jPanel1,
                                            GroupLayout.PREFERRED_SIZE,
                                            GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE
                                        )
                                        .addGap(0, 0, Short.MAX_VALUE.toInt())
                                )
                        )
                        .addContainerGap()
                )
        )
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(
                            jPanel1,
                            GroupLayout.PREFERRED_SIZE,
                            GroupLayout.DEFAULT_SIZE,
                            GroupLayout.PREFERRED_SIZE
                        )
                        .addPreferredGap(
                            LayoutStyle.ComponentPlacement.RELATED,
                            GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE.toInt()
                        )
                        .addGroup(
                            layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(paypalButton)
                                .addComponent(closeButton)
                        )
                        .addContainerGap()
                )
        )
        pack()
    } // </editor-fold>//GEN-END:initComponents

    private fun paypalButtonActionPerformed(evt: ActionEvent) { //GEN-FIRST:event_paypalButtonActionPerformed
        IO.openWeb(
            app,
            this,
            "https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=bunnyspa242%40gmail.com&currency_code=USD&source=url"
        )
    } //GEN-LAST:event_paypalButtonActionPerformed

    private fun closeButtonActionPerformed(evt: ActionEvent) { //GEN-FIRST:event_closeButtonActionPerformed
        dispose()
    } //GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private var closeButton: JButton? = null
    private var jPanel1: JPanel? = null
    private var paypalButton: JButton? = null
    private var paypalQRDescLabel: JLabel? = null
    private var paypalQRLabel: JLabel? = null // End of variables declaration//GEN-END:variables

    companion object {
        fun getInstance(app: App): DonationDialog {
            return DonationDialog(app)
        }
    }

    init {
        initComponents()
        this.app = app
        init()
    }
}