package main.ui.help

import main.App
import main.ui.resource.AppImage
import main.ui.resource.AppText
import main.util.Fn
import java.awt.event.ActionEvent
import javax.swing.*

/**
 *
 * @author Bunnyspa
 */
class HelpProxyDialog(private val app: App) : JDialog() {
    private fun init() {
        title = app.getText(AppText.HELP_PROXY)
        jLabel1!!.icon = AppImage.HELP_PROXY
        descLabel!!.text = app.getText(AppText.HELP_PROXY_DESC)
        closeButton!!.text = app.getText(AppText.ACTION_CLOSE)
        addListeners()
        pack()
    }

    private fun addListeners() {
        Fn.addEscDisposeListener(this)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {
        closeButton = JButton()
        jLabel1 = JLabel()
        descLabel = JLabel()
        defaultCloseOperation = DISPOSE_ON_CLOSE
        title = "프록시 설정 방법"
        modalityType = ModalityType.APPLICATION_MODAL
        isResizable = false
        type = Type.UTILITY
        closeButton!!.text = "닫기"
        closeButton!!.addActionListener { evt: ActionEvent -> closeButtonActionPerformed(evt) }
        descLabel!!.text = "WARNING"
        val layout = GroupLayout(contentPane)
        contentPane.layout = layout
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(
                                    jLabel1,
                                    GroupLayout.DEFAULT_SIZE,
                                    GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE.toInt()
                                )
                                .addGroup(
                                    layout.createSequentialGroup()
                                        .addComponent(descLabel, GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE.toInt())
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(closeButton)
                                )
                        )
                        .addContainerGap()
                )
        )
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE.toInt())
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(
                            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(descLabel, GroupLayout.Alignment.TRAILING)
                                .addComponent(closeButton, GroupLayout.Alignment.TRAILING)
                        )
                        .addContainerGap()
                )
        )
        pack()
    } // </editor-fold>//GEN-END:initComponents

    private fun closeButtonActionPerformed(evt: ActionEvent) { //GEN-FIRST:event_closeButtonActionPerformed
        dispose()
    } //GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private var closeButton: JButton? = null
    private var descLabel: JLabel? = null
    private var jLabel1: JLabel? = null // End of variables declaration//GEN-END:variables

    init {
        initComponents()
        init()
    }
}